/* eslint-disable @next/next/no-img-element -- Brand SVGs remain vector assets and do not need raster optimization. */
import { plans, siteContent } from './site-content';
const Arrow=()=> <span aria-hidden="true">↗</span>;
const Check=()=> <span className="check" aria-hidden="true">✓</span>;

export default function Home(){return <main>
  <header className="site-header"><a className="brand" href="#home" aria-label="TowCalc home"><img className="brand-logo" src="/towcalc_fulllogo_light.svg" alt="TowCalc Pro" width="220" height="68"/></a><nav aria-label="Main navigation"><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#why">Why TowCalc</a></nav><div className="header-actions"><a className="login" href="https://app.towcalc.com">Log in</a><a className="button button-small" href="https://app.towcalc.com">Get started <Arrow/></a></div></header>
  <section className="hero" id="home"><div className="hero-grid" aria-hidden="true"/><div className="hero-copy"><div className="eyebrow"><span/> {siteContent.hero.eyebrow}</div><h1>{siteContent.hero.headlineLine1}<br/><em>{siteContent.hero.headlineLine2}</em></h1><p>{siteContent.hero.description}</p><div className="hero-actions"><a className="button" href="https://app.towcalc.com">{siteContent.hero.primaryCta} <Arrow/></a><a className="text-link" href="#how">{siteContent.hero.secondaryCta} <span>↓</span></a></div><div className="trust-line"><span>{siteContent.hero.trustLeft}</span><span>•</span><span>{siteContent.hero.trustRight}</span></div></div>
    <div className="quote-card" aria-label="TowCalc quote preview"><div className="quote-card-top"><div><span className="mini-label">NEW QUOTE</span><strong>Heavy-duty transport</strong></div><span className="status">READY</span></div><div className="route-row"><div className="route-track"><i/><span/><i/></div><div className="route-copy"><p><span>Pickup</span>Fort Worth, TX</p><p><span>Destination</span>Arlington, TX</p></div><div className="miles"><strong>18.4</strong><span>MILES</span></div></div><div className="quote-lines"><div><span>Hook & load</span><strong>$175.00</strong></div><div><span>Loaded mileage · 18.4 mi</span><strong>$92.00</strong></div><div><span>Equipment surcharge</span><strong>$45.00</strong></div></div><div className="quote-total"><span>QUOTE TOTAL<small>Based on your configured rates</small></span><strong>$312.00</strong></div><button type="button">Generate professional quote <Arrow/></button><div className="floating-chip chip-one"><span>✓</span> Rate rules applied</div><div className="floating-chip chip-two"><span>◎</span> Trip time calculated</div></div>
  </section>
  <section className="proof-strip" aria-label="TowCalc benefits">{siteContent.proof.map(item=><div key={item.value}><strong>{item.value}</strong><span>{item.label}</span></div>)}</section>
  <section className="section features" id="features"><div className="section-intro"><div className="eyebrow"><span/> {siteContent.features.eyebrow}</div><h2>{siteContent.features.headlineLine1}<br/>{siteContent.features.headlineLine2}</h2><p>{siteContent.features.description}</p></div><div className="feature-grid">
    <article className="feature-card"><div className="number">01</div><div className="feature-icon">$</div><h3>{siteContent.features.cards[0].title}</h3><p>{siteContent.features.cards[0].description}</p><div className="rate-visual billing-modes"><div className="billing-mode active"><span>HOURLY MODE</span><b>$225 / hr</b><small>Estimated time × hourly rate</small></div><div className="billing-mode"><span>PER-MILE MODE</span><b>$5.00 / mi</b><small>Loaded miles × mileage rate</small></div></div></article>
    <article className="feature-card dark-card"><div className="number">02</div><div className="feature-icon">⌖</div><h3>{siteContent.features.cards[1].title}</h3><p>{siteContent.features.cards[1].description}</p><div className="map-visual"><span className="road road-a"/><span className="road road-b"/><i className="pin pin-a"/><i className="pin pin-b"/><b>18.4 MI</b></div></article>
    <article className="feature-card"><div className="number">03</div><div className="feature-icon">▤</div><h3>{siteContent.features.cards[2].title}</h3><p>{siteContent.features.cards[2].description}</p><div className="doc-visual"><span>TOW QUOTE</span><i/><i/><i/><b>$312.00</b></div></article>
  </div></section>
  <section className="workflow" id="how"><div className="workflow-copy"><div className="eyebrow light"><span/> {siteContent.workflow.eyebrow}</div><h2>{siteContent.workflow.headlineLine1}<br/>{siteContent.workflow.headlineLine2}</h2><p>{siteContent.workflow.description}</p></div><ol>{siteContent.workflow.steps.map((step,index)=><li key={step.title}><span>{String(index+1).padStart(2,'0')}</span><div><strong>{step.title}</strong><p>{step.description}</p></div></li>)}</ol></section>
  <section className="section portal-section"><div className="portal-card"><div className="portal-copy"><div className="eyebrow"><span/> {siteContent.portal.eyebrow}</div><h2>{siteContent.portal.headline}</h2><p>{siteContent.portal.description}</p><ul>{siteContent.portal.bullets.map(bullet=><li key={bullet}><Check/> {bullet}</li>)}</ul></div><div className="portal-ui"><div className="portal-sidebar"><div className="tiny-brand">TC</div><i/><i/><i/><i/></div><div className="portal-main"><span>CLIENT PORTAL</span><h4>Request a quote</h4><label>Pickup location<b>1200 Commerce St, Dallas</b></label><label>Destination<b>Arlington, TX</b></label><div className="portal-result"><span>ESTIMATED TOTAL</span><strong>$486.00</strong></div></div></div></div></section>
  <section className="section pricing" id="pricing"><div className="pricing-heading"><div><div className="eyebrow"><span/> {siteContent.pricing.eyebrow}</div><h2>{siteContent.pricing.headlineLine1}<br/>{siteContent.pricing.headlineLine2}</h2></div><p>{siteContent.pricing.description}</p></div><div className="plan-grid">{plans.map(plan=><article className={`plan ${plan.featured?'featured':''}`} key={plan.name}>{plan.featured&&<div className="popular">MOST POPULAR</div>}<span className="plan-eyebrow">{plan.eyebrow}</span><h3>{plan.name}</h3><p>{plan.description}</p><div className="price"><strong>{plan.price}</strong>{plan.price!=='Custom'&&<span>/ month</span>}</div><div className="annual">{plan.price==='Custom'?plan.annual:`or ${plan.annual} / year`}</div><a className={plan.featured?'button':'outline-button'} href="https://app.towcalc.com">{plan.price==='Custom'?'Talk to us':'Get started'} <Arrow/></a><div className="includes">WHAT’S INCLUDED</div><ul>{plan.features.map(feature=><li key={feature}><Check/> {feature}</li>)}</ul></article>)}</div><div className="onboarding"><div><span className="feature-icon">→</span><div><strong>{siteContent.pricing.onboardingTitle}</strong><p>{siteContent.pricing.onboardingDescription}</p></div></div><a href="https://app.towcalc.com">{siteContent.pricing.onboardingLink} <Arrow/></a></div></section>
  <section className="why" id="why"><div className="why-copy"><div className="eyebrow light"><span/> {siteContent.why.eyebrow}</div><h2>{siteContent.why.headlineLine1}<br/>{siteContent.why.headlineLine2}</h2><p>{siteContent.why.description}</p><a className="text-link light-link" href="#features">{siteContent.why.link} <Arrow/></a></div><blockquote><span>“</span><p>{siteContent.why.quote}</p><cite>{siteContent.why.quoteLabel}</cite></blockquote></section>
  <section className="final-cta"><div className="eyebrow"><span/> {siteContent.finalCta.eyebrow}</div><h2>{siteContent.finalCta.headlineLine1}<br/>{siteContent.finalCta.headlineLine2}</h2><p>{siteContent.finalCta.description}</p><a className="button" href="https://app.towcalc.com">{siteContent.finalCta.button} <Arrow/></a></section>
  <footer><a className="brand" href="#home"><img className="brand-logo footer-logo" src="/towcalc_fulllogo_light.svg" alt="TowCalc Pro" width="220" height="68"/></a><p>{siteContent.footer.tagline}</p><div><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#why">Why TowCalc</a><a href="https://app.towcalc.com">Log in</a></div><small>{siteContent.footer.legal}</small></footer>
</main>}
